name: battery_info
description: Flutter plugin providing detailed information about the device battery (level, health, charging status, etc.). Currently only supports Android
version: 1.0.1
homepage: https://github.com/igrik12/battery_info.git

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.igrik12.battery_info
        pluginClass: BatteryInfoPlugin
      iso:
        pluginClass: BatteryInfoPlugin
